# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4904a82815541c3776f87b3268f92d70"
name = "Vendor Alert"
handle = "vendor-alert"
application_url = "https://baghdad-guestbook-cl-fragrances.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/api/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = [
  "orders/cancelled",
  "orders/create",
  "orders/fulfilled",
  "orders/paid",
  "orders/updated"
]
  uri = "/api/webhooks/orders"
  include_fields = [
  "id",
  "name",
  "line_items",
  "financial_status",
  "fulfillment_status",
  "created_at",
  "updated_at"
]

  [[webhooks.subscriptions]]
  topics = [ "products/create", "products/delete", "products/update" ]
  uri = "/api/webhooks/products"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_products"

[auth]
redirect_urls = ["https://baghdad-guestbook-cl-fragrances.trycloudflare.com/auth/callback", "https://baghdad-guestbook-cl-fragrances.trycloudflare.com/auth/shopify/callback", "https://baghdad-guestbook-cl-fragrances.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
