# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "74db907f6dd1046c885f946d7c55e5bc"
name = "Vendor Alert"
handle = "vendor-alert"
application_url = "https://town-mailman-selection-hat.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app-uninstalled"

  [[webhooks.subscriptions]]
  topics = [
    "orders/cancelled",
    "orders/create",
    "orders/updated"
  ]
  uri = "/webhooks/orders"
  include_fields = [
    "id",
    "name",
    "line_items",
    "financial_status",
    "fulfillment_status",
    "created_at",
    "updated_at"
  ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_products"

[auth]
redirect_urls = ["https://town-mailman-selection-hat.trycloudflare.com/auth/callback", "https://town-mailman-selection-hat.trycloudflare.com/auth/shopify/callback", "https://town-mailman-selection-hat.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
