# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4904a82815541c3776f87b3268f92d70"
name = "Vendor Alert"
handle = "vendor-alert"
application_url = "https://remembered-worship-error-give.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true 

[webhooks]
api_version = "2025-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://remembered-worship-error-give.trycloudflare.com/auth/callback", "https://remembered-worship-error-give.trycloudflare.com/auth/shopify/callback", "https://remembered-worship-error-give.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
